"""
Generates synthetic (invoice_text, structured_json) training pairs for
Phase 7's LoRA fine-tuning.

STRATEGY (JSON-first, ground truth by construction):
  1. Programmatically generate a target ExtractedInvoice-shaped JSON object
     using controlled randomization - vendor, line items, prices, dates,
     currency, and deliberately omitted optional fields.
  2. Ask Gemini to render THAT EXACT JSON as realistic, messy invoice text -
     varied formatting, OCR-like noise, abbreviations - without changing
     any of the underlying values.
  3. Optionally sanity-check each pair by running the generated text back
     through the project's own extraction pipeline (on the real Groq
     production baseline) and comparing key fields, to catch cases where
     the rendering lost or altered data.

This is deliberately different from a "generate text, then extract it to
get the label" approach: here the JSON is correct BY CONSTRUCTION, so
labels are never contaminated by the extraction pipeline's own errors.

Rendering runs on Gemini 3.1 Flash-Lite and the roundtrip quality check
runs on Groq's production baseline model - two different providers, so
the training data isn't generated and graded by the same model family.

IMPORTANT - this script produces SYNTHETIC training data only. Per the
project's documented methodology, a small held-out set of REAL invoices
(not generated by this script) must also be collected and used for
Phase 8 benchmark evaluation, so accuracy claims aren't purely
synthetic-on-synthetic. See the reminder printed at the end of this
script, and populate data/real_holdout/ manually.

Usage:
    python scripts/generate_synthetic_data.py --n 400

    # Groq's free tier caps gpt-oss-120b at ~200k tokens/day, and this is
    # used for the roundtrip check on every example. Gemini 3.1 Flash-Lite
    # (rendering) has its own separate daily/per-minute cap - check your
    # actual limits at aistudio.google.com before a big run. Spread
    # generation across multiple days if needed:
    python scripts/generate_synthetic_data.py --n 100 --append   # day 1
    python scripts/generate_synthetic_data.py --n 100 --append   # day 2
    python scripts/generate_synthetic_data.py --n 100 --append   # day 3
    python scripts/generate_synthetic_data.py --n 100 --append   # day 4
    # Each run adds to the existing dataset rather than overwriting it,
    # and train/test split membership is stable across runs (hash-based,
    # not randomly reshuffled), so no example silently moves between
    # train and test as the dataset grows.

Outputs:
    data/synthetic/train.jsonl        (prompt/completion formatted, for training)
    data/synthetic/test.jsonl         (raw_text + ground-truth JSON, for eval)
    data/synthetic/raw_pairs.jsonl    (unfiltered, for audit/debugging)
"""

import argparse
import hashlib
import json
import random
import string
import time
from datetime import date, timedelta
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path

from invoice_extractor.clients.groq_client import GroqClient
from invoice_extractor.clients.gemini_client import GeminiClient
from invoice_extractor.extraction import extract_invoice
from invoice_extractor.prompts import build_extraction_prompt

# Renders invoice JSON -> messy text using Gemini 3.1 Flash-Lite, a
# smaller/cheaper model on a DIFFERENT provider than the production
# baseline, since this is a simpler task than extraction itself and
# doesn't need to be the production baseline model. The roundtrip quality
# check (below) still uses the real production baseline (GroqClient() with
# no override, i.e. settings.groq_model_name) since that check's validity
# depends on matching what production actually runs.
RENDERING_MODEL = "gemini-3.1-flash-lite"

# --- Data pools for programmatic JSON generation ------------------------

VENDOR_TEMPLATES = [
    ("{name} Electronics", ["USB-C Cable", "Wireless Mouse", "Laptop Stand", "HDMI Adapter", "Bluetooth Speaker", "Power Bank"]),
    ("{name} Hardware", ["Hammer", "Screwdriver Set", "Nails (box)", "Paint (gallon)", "Drill Bit Set", "Measuring Tape"]),
    ("{name} Bistro", ["Grilled Chicken", "Caesar Salad", "House Wine (glass)", "Espresso", "Tiramisu", "Garlic Bread"]),
    ("{name} Consulting", ["Strategy Session (hr)", "Report Drafting (hr)", "On-site Visit", "Follow-up Call (hr)"]),
    ("{name} Auto Repair", ["Oil Change", "Brake Pad Replacement", "Tire Rotation", "Diagnostic Fee", "Wiper Blades"]),
    ("{name} Print Shop", ["Business Cards (100)", "Flyer Printing (50)", "Banner (3x6ft)", "Binding Service"]),
    ("{name} Cleaning Co", ["Standard Clean", "Deep Clean Add-on", "Window Cleaning", "Carpet Shampoo"]),
    ("{name} Bookstore", ["Paperback Novel", "Notebook", "Bookmark Set", "Gift Wrap"]),
]

NAME_PREFIXES = [
    "ACME", "Summit", "Riverside", "Golden Gate", "Northstar", "Cedar",
    "Blue Ridge", "Pioneer", "Harbor", "Union", "Maple", "Crestwood",
    "Lakeside", "Ironclad", "Meridian", "Vista", "Evergreen",
]

CURRENCIES = ["USD", "USD", "USD", "USD", "EUR", "GBP", "INR"]  # weighted toward USD

NOISE_STYLES = [
    "a clean, structured invoice with clear labeled fields",
    "a messy thermal-printer receipt with abbreviations and tight spacing",
    "a minimal handwritten-style receipt, slightly OCR-noisy (odd spacing or a stray character here and there)",
    "a formal business invoice with a letterhead-style header",
    "a casual receipt with items listed in a loose, unaligned way",
]


def _random_decimal(low: float, high: float) -> Decimal:
    value = round(random.uniform(low, high), 2)
    return Decimal(str(value)).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)


def _random_invoice_number() -> str:
    return f"INV-{random.randint(1000, 9999)}-{''.join(random.choices(string.ascii_uppercase, k=2))}"


def _random_date() -> str:
    d = date.today() - timedelta(days=random.randint(0, 730))
    return d.isoformat()


def generate_target_invoice() -> dict:
    """
    Programmatically builds one ExtractedInvoice-shaped JSON object with
    controlled randomization. This IS the ground-truth label - nothing
    downstream ever needs to re-derive it.
    """
    template_name, item_pool = random.choice(VENDOR_TEMPLATES)
    vendor_name = template_name.format(name=random.choice(NAME_PREFIXES))
    currency = random.choice(CURRENCIES)

    num_items = random.randint(1, 8)
    chosen_items = random.sample(item_pool, min(num_items, len(item_pool)))
    while len(chosen_items) < num_items:
        chosen_items.append(random.choice(item_pool))

    line_items = []
    running_subtotal = Decimal("0.00")
    for description in chosen_items:
        # ~35% of items are whole-item priced (no quantity/unit_price breakdown)
        if random.random() < 0.35:
            quantity = None
            unit_price = None
            total = _random_decimal(5, 200)
        else:
            quantity = random.choice([1, 1, 2, 3, 4, 1.5, 2.5])
            unit_price = _random_decimal(3, 80)
            total = (Decimal(str(quantity)) * unit_price).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)

        running_subtotal += total
        line_items.append({
            "description": description,
            "quantity": quantity,
            "unit_price": str(unit_price) if unit_price is not None else None,
            "total": str(total),
        })

    omit_invoice_number = random.random() < 0.25
    omit_date = random.random() < 0.2
    omit_tax = random.random() < 0.3
    omit_subtotal = random.random() < 0.3

    subtotal = running_subtotal
    if not omit_tax:
        tax_rate = random.choice([0.05, 0.07, 0.08, 0.0875, 0.1])
        tax_amount = (subtotal * Decimal(str(tax_rate))).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
    else:
        tax_amount = Decimal("0.00")

    total_amount = subtotal + tax_amount

    invoice = {
        "vendor_name": vendor_name,
        "invoice_number": None if omit_invoice_number else _random_invoice_number(),
        "invoice_date": None if omit_date else _random_date(),
        "line_items": line_items,
        "subtotal": None if omit_subtotal else str(subtotal),
        "tax_amount": None if omit_tax else str(tax_amount),
        "total_amount": str(total_amount),
        "currency": currency,
    }
    return invoice


# --- Step 2: ask Gemini to render the JSON as messy text -----------------

def build_rendering_prompt(invoice: dict) -> str:
    """
    Asks the rendering model to turn a ground-truth JSON object into
    realistic invoice text WITHOUT changing any values. This is a
    rendering task, not a creative one - the model must preserve every
    number and name exactly.
    """
    style = random.choice(NOISE_STYLES)
    return f"""You will be given structured invoice data as JSON. Render it as
{style}.

RULES - follow exactly:
- Do NOT change any vendor name, item description, quantity, price, date,
  or total. Use the exact values given.
- You MAY reformat, reorder slightly, abbreviate labels, add typical
  invoice boilerplate (e.g. "Thank you for your business"), or introduce
  minor OCR-like noise (odd spacing, a stray character) IF the style
  calls for it.
- Do NOT add any line items, fields, or values that are not in the JSON.
- If a field is null in the JSON, do NOT include that field in the output
  at all (e.g. if invoice_number is null, don't show any invoice number).
- Output ONLY the raw invoice/receipt text - no explanations, no markdown,
  no JSON, no preamble.

JSON:
{json.dumps(invoice, ensure_ascii=False)}
"""


def render_invoice_text(rendering_client, invoice: dict) -> str:
    prompt = build_rendering_prompt(invoice)
    return rendering_client.extract_raw(prompt).strip()


# --- Step 3: optional roundtrip quality check -----------------------------

def roundtrip_check_ok(baseline_client: GroqClient, raw_text: str, target_invoice: dict) -> bool:
    """
    Sanity check: run the generated text back through the project's own
    extraction pipeline, using the REAL PRODUCTION BASELINE MODEL (not the
    rendering model), and confirm it recovers a roughly matching total
    and vendor name. This does NOT replace the ground-truth label - it
    only filters out cases where the rendering was so garbled or lossy
    that even a good extractor couldn't recover the key facts, which
    would indicate the generated TEXT (not the label) is low quality.

    Using the production baseline here (not the rendering model) matters:
    this check is meant to simulate "would our real system correctly
    extract this text," so it needs to run the same model the real
    system runs.
    """
    result = extract_invoice(raw_text, baseline_client)
    if not result.success or result.invoice is None:
        return False

    try:
        recovered_total = Decimal(str(result.invoice.total_amount))
        target_total = Decimal(str(target_invoice["total_amount"]))
    except Exception:
        return False

    totals_close = abs(recovered_total - target_total) <= Decimal("0.05")
    vendor_present = target_invoice["vendor_name"].split()[0].lower() in result.invoice.vendor_name.lower()

    return totals_close and vendor_present


# --- Stable train/test assignment (survives multi-day, multi-run batches) ---

def is_test_example(raw_text: str, test_split: float) -> bool:
    """
    Deterministically assigns an example to the test set based on a hash
    of its own text, rather than a random shuffle. This matters once
    generation happens across multiple runs/days (--append): a random
    shuffle would reassign old examples between train/test each run,
    silently leaking previously-train-only examples into the held-out
    set (or vice versa) over time. Hashing keeps each example's
    train/test membership stable forever, regardless of when it was
    generated or how many more examples get added later.
    """
    digest = hashlib.sha256(raw_text.encode("utf-8")).hexdigest()
    bucket = int(digest, 16) % 10000
    return bucket < int(test_split * 10000)


# --- Formatting for the LoRA training script ----------------------------

# Uses the project's REAL prompt-building function (prompts.py) directly,
# rather than a hand-copied template - guarantees the fine-tuned model is
# trained on the exact same input shape it will be given at inference and
# benchmark time. If build_extraction_prompt() ever changes, this stays
# in sync automatically instead of silently drifting.


def format_training_example(raw_text: str, invoice_json: dict) -> dict:
    prompt = build_extraction_prompt(raw_text)
    completion = json.dumps(invoice_json, ensure_ascii=False)
    return {"prompt": prompt, "completion": completion}


def main():
    parser = argparse.ArgumentParser(description="Generate synthetic invoice training data (JSON-first strategy)")
    parser.add_argument("--n", type=int, default=400, help="Number of examples to attempt")
    parser.add_argument("--test-split", type=float, default=0.15, help="Fraction of SYNTHETIC data held out for eval")
    parser.add_argument("--out-dir", type=str, default="data/synthetic", help="Output directory")
    parser.add_argument("--sleep", type=float, default=4.2, help="Seconds between rendering calls (Gemini 3.1 Flash-Lite free tier: 15 RPM)")
    parser.add_argument("--skip-roundtrip-check", action="store_true", help="Skip the extraction-based quality filter (faster, lower quality)")
    parser.add_argument("--append", action="store_true",
                         help="Load any existing raw_pairs.jsonl first and add this run's "
                              "new examples on top, instead of overwriting. Use this to spread "
                              "generation across multiple days to stay under provider free-tier "
                              "daily caps (Gemini 3.1 Flash-Lite RPD, Groq token/day cap).")
    args = parser.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    rendering_client = GeminiClient(model_name=RENDERING_MODEL)
    baseline_client = GroqClient()  # unchanged - stays the real production baseline for roundtrip check

    raw_pairs = []
    seen_texts = set()

    raw_path = out_dir / "raw_pairs.jsonl"

    if args.append:
        if raw_path.exists():
            with open(raw_path, "r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue
                    pair = json.loads(line)
                    raw_pairs.append(pair)
                    seen_texts.add(pair["raw_text"])
            print(f"--append: loaded {len(raw_pairs)} existing examples from {raw_path}")
    elif raw_path.exists():
        # Not appending - start fresh instead of silently mixing old data
        # into the "w" mode write at the end, since we now write
        # incrementally in "a" mode below.
        raw_path.unlink()

    # Write each accepted pair to disk immediately as it's found, instead
    # of only at the very end of the run. If Groq's roundtrip-check quota
    # (or anything else) causes a crash mid-run, everything accepted
    # before the crash is already safely on disk instead of lost.
    raw_file = open(raw_path, "a", encoding="utf-8")

    rendered = 0
    discarded_roundtrip = 0
    discarded_error = 0
    discarded_duplicate = 0

    print(f"Generating {args.n} synthetic invoices (JSON-first strategy)...")
    try:
        for i in range(args.n):
            target_invoice = generate_target_invoice()

            try:
                raw_text = render_invoice_text(rendering_client, target_invoice)
            except Exception as e:
                print(f"  [{i+1}/{args.n}] rendering call failed: {e}")
                discarded_error += 1
                time.sleep(args.sleep)
                continue

            if not raw_text:
                discarded_error += 1
                time.sleep(args.sleep)
                continue

            if not args.skip_roundtrip_check:
                time.sleep(args.sleep)  # second call coming up (extraction, on Groq baseline)
                try:
                    ok = roundtrip_check_ok(baseline_client, raw_text, target_invoice)
                except Exception as e:
                    # Groq quota exhausted mid-run, or any other API failure -
                    # discard this example and keep going, rather than crashing
                    # and losing the rest of the run. Already-accepted pairs
                    # are safe on disk regardless, since we write incrementally.
                    print(f"  [{i+1}/{args.n}] roundtrip check failed (error): {e}")
                    discarded_error += 1
                    time.sleep(args.sleep)
                    continue
                if not ok:
                    discarded_roundtrip += 1
                    time.sleep(args.sleep)
                    continue

            if raw_text in seen_texts:
                # Rare (hash-level dedup, not expected often) but cheap to guard
                # against double-counting if a run is interrupted and re-run.
                discarded_duplicate += 1
                time.sleep(args.sleep)
                continue

            pair = {"raw_text": raw_text, "invoice": target_invoice}
            raw_pairs.append(pair)
            seen_texts.add(raw_text)
            raw_file.write(json.dumps(pair, ensure_ascii=False) + "\n")
            raw_file.flush()  # ensure it's actually on disk, not just buffered
            rendered += 1

            if (i + 1) % 20 == 0:
                print(f"  [{i+1}/{args.n}] {rendered} kept this run, "
                      f"{discarded_roundtrip} failed roundtrip check, "
                      f"{discarded_error} errored, {discarded_duplicate} duplicates")

            time.sleep(args.sleep)
    finally:
        raw_file.close()

    print(f"\nDone. {rendered} new valid pairs kept this run, "
          f"{discarded_roundtrip} discarded (failed roundtrip check), "
          f"{discarded_error} discarded (generation error), "
          f"{discarded_duplicate} discarded (duplicate).")
    print(f"Total accumulated pairs (including prior runs, if --append): {len(raw_pairs)}")
    print(f"Wrote {len(raw_pairs)} total raw pairs to {raw_path}")

    if len(raw_pairs) == 0:
        print("No valid pairs available - aborting before writing train/test splits.")
        return

    # Deterministic hash-based split (not random.shuffle) - see
    # is_test_example() docstring for why this matters with --append.
    train_pairs = [p for p in raw_pairs if not is_test_example(p["raw_text"], args.test_split)]
    test_pairs = [p for p in raw_pairs if is_test_example(p["raw_text"], args.test_split)]

    train_path = out_dir / "train.jsonl"
    test_path = out_dir / "test.jsonl"

    with open(train_path, "w", encoding="utf-8") as f:
        for pair in train_pairs:
            example = format_training_example(pair["raw_text"], pair["invoice"])
            f.write(json.dumps(example, ensure_ascii=False) + "\n")

    with open(test_path, "w", encoding="utf-8") as f:
        for pair in test_pairs:
            f.write(json.dumps(pair, ensure_ascii=False) + "\n")

    print(f"Wrote {len(train_pairs)} training examples to {train_path}")
    print(f"Wrote {len(test_pairs)} held-out SYNTHETIC test examples to {test_path}")

    print("""
============================================================
REMINDER - real-invoice holdout still needed:
This script produces SYNTHETIC data only. Per the project's
documented methodology, also collect a small set (10-20) of
REAL invoices/receipts - e.g. your own receipts, public
sample-invoice datasets - and save them to:

    data/real_holdout/real_test.jsonl

...in the same {"raw_text": ..., "invoice": ...} format as
test.jsonl, hand-labeling the "invoice" field yourself.
Phase 8's benchmark should report accuracy on BOTH the
synthetic test set AND this real holdout set, so the
fine-tuned model's numbers aren't purely synthetic-on-synthetic.
============================================================
""")


if __name__ == "__main__":
    main()